#!/usr/bin/env bash
# Surface estack's shared instructions to both tools, with host-specific overlays.
#
# Claude Code reads ~/CLAUDE.md and appends ~/CLAUDE.local.md after it. The
# Claude side is a live symlink to an overlay that imports shared instructions.
#
# Codex starts its AGENTS.md walk at the repository root and never reads your
# home ~/CLAUDE.md, and it has no *.local append. Its only override mechanism is
# AGENTS.override.md, which replaces the base file at its level. So the Codex
# side is a generated file combining your home instructions with estack's delta.
#
# This is Nix-agnostic on purpose: ~/CLAUDE.md is read as opaque rendered text
# (whatever produced it), and if it's absent the Codex file is the shared
# estack instructions alone.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHARED_SRC="$REPO_DIR/home/estack-instructions.md"
CLAUDE_SRC="$REPO_DIR/home/claude-instructions.md"
CODEX_SRC="$REPO_DIR/home/codex-instructions.md"
OLD_SRC="$REPO_DIR/home/estack.md"
MANAGED_MARKER="generated by estack (scripts/install-home-instructions.sh)"

[ -f "$SHARED_SRC" ] || { echo "error: missing $SHARED_SRC" >&2; exit 1; }
[ -f "$CLAUDE_SRC" ] || { echo "error: missing $CLAUDE_SRC" >&2; exit 1; }
[ -f "$CODEX_SRC" ] || { echo "error: missing $CODEX_SRC" >&2; exit 1; }

# --- Claude Code: ~/CLAUDE.local.md -> Claude overlay (live symlink) ---
CC_LOCAL="${CLAUDE_LOCAL_MD:-$HOME/CLAUDE.local.md}"
if [ -L "$CC_LOCAL" ]; then
  if [ "$(readlink "$CC_LOCAL")" = "$CLAUDE_SRC" ]; then
    echo "claude: ~/CLAUDE.local.md already linked"
  elif [ "$(readlink "$CC_LOCAL")" = "$SHARED_SRC" ] || [ "$(readlink "$CC_LOCAL")" = "$OLD_SRC" ]; then
    ln -sfn "$CLAUDE_SRC" "$CC_LOCAL"
    echo "claude: updated ~/CLAUDE.local.md -> $CLAUDE_SRC"
  else
    echo "claude: $CC_LOCAL is a symlink elsewhere; leaving it alone"
  fi
elif [ -e "$CC_LOCAL" ]; then
  echo "claude: $CC_LOCAL exists and is not a symlink; leaving it alone"
else
  ln -s "$CLAUDE_SRC" "$CC_LOCAL"
  echo "claude: linked ~/CLAUDE.local.md -> $CLAUDE_SRC"
fi

# --- Codex: ~/.codex/AGENTS.override.md = home instructions + estack delta ---
CODEX_DIR="${CODEX_HOME:-$HOME/.codex}"
OVERRIDE="$CODEX_DIR/AGENTS.override.md"
HOME_CLAUDE="${HOME_CLAUDE_MD:-$HOME/CLAUDE.md}"
mkdir -p "$CODEX_DIR"

if [ -e "$OVERRIDE" ] && ! grep -qF "$MANAGED_MARKER" "$OVERRIDE" 2>/dev/null; then
  echo "codex: $OVERRIDE exists and is not estack-managed; leaving it alone"
else
  {
    echo "<!-- $MANAGED_MARKER. Do not edit; re-run the script to regenerate -->"
    echo
    if [ -f "$HOME_CLAUDE" ]; then
      cat "$HOME_CLAUDE"
      echo
    fi
    cat "$SHARED_SRC"
    echo
    cat "$CODEX_SRC"
  } > "$OVERRIDE"
  echo "codex: wrote $OVERRIDE"
fi

echo
echo "Done. Start a new Claude Code session / restart Codex to pick these up."
